refactor: configureSession as params (#240)
In chat SDK, because of the instance check in SessionHandler,
customer cannot use SessionHandler when using self-service or umd
builds.

Therefore, we are refactoring it to also handle it as a general object.

example
```ts
const chatbotConfigs = {};

chatbotConfigs.userId = 'USER_ID';
chatbotConfigs.configureSession = () => ({
    onSessionTokenRequired: (resolve, reject) => {
      issueSessionToken('USER_ID')
        .then(token => resolve(token));
        .catch(err => reject(err));
    },
    onSessionRefreshed: () => {
      // Handle session refresh
    },
    onSessionError: (err) => {
      // Handle session error
    },
    onSessionClosed: () => {
      // Handle session closure
    };
})
```